<?php

declare(strict_types=1);

// The site's composer project builds vendor/, so the engine registers its own namespace.
(require __DIR__ . '/vendor/autoload.php')->addPsr4('Drupack\\Support\\', __DIR__ . '/support');

require __DIR__ . '/process.php';

use Drupack\Support\SiteData;
use Symfony\Component\Filesystem\Path;

// The option set also reaches a reader through runtime/entrypoint.go's usage and
// docs/cli.md. application/tests/launch_test.php asserts all three against options().
const HELP = <<<'TEXT'
Usage: %1$s [start] [OPTIONS]
       %1$s drush [OPTIONS] DRUSH_COMMAND
       %1$s stop [--data-dir PATH]

Options:
  --data-dir PATH            Site data directory, ./data by default
  --listen IP:PORT           Listener address, 127.0.0.1 on the site's port by default
  --host HOST                Permitted request host, localhost by default
  --files-dir PATH           Public files directory, files in Site data by default
  --database sqlite|mysql|pgsql
                             Database backend for a first start, sqlite by default
  --db-host HOST             Database server, for mysql and pgsql
  --db-port PORT             Database port, 3306 for mysql and 5432 for pgsql
  --db-name NAME             Database name, for mysql and pgsql
  --db-user NAME             Database user, for mysql and pgsql
  --db-password PASSWORD     Database password, for mysql and pgsql
  --admin-user NAME          Administrator account for a first start, admin by default
  --admin-password PASSWORD  Administrator password for a first start, generated by default
  --site-name NAME           Site name for a first start, the packaged site's name by default
  --no-browser               Do not open a browser
  --foreground               Serve in this terminal until a signal stops the site

docs/cli.md explains every option.
TEXT;

// The server runs from the application directory, which every site of a release
// shares, so a path the reader wrote relative to their own directory resolves
// against the one they started in.
function fromStartDirectory(string $path): string
{
    $start = environment('DRUPACK_RUNTIME_CWD');
    if ($start === null || Path::isAbsolute($path)) {
        return $path;
    }
    return Path::makeAbsolute($path, $start);
}

// The application the site runs: the release's shared copy, or once a start or `drush` has
// checked it, the site's own copy in Site data. The launcher exports the shared copy.
function application(): string
{
    return getenv('DRUPACK_RUNTIME_APP_DIR');
}

// A site whose contract names writable directories runs its own application, laid in
// Site data. A start lays it under the Serving lease. `drush` takes no lease, so it only
// checks that the last start laid this release.
function useSiteApplication(SiteData $site, bool $drush): void
{
    $data = $site->directory;
    $launcher = getenv('DRUPACK_RUNTIME_LAUNCHER');
    $descriptors = [0 => ['file', nullDevice(), 'r'], 1 => STDOUT, 2 => STDERR];
    if ($drush) {
        if (process($launcher, ['lay-app', '--check', $data], $descriptors, $data, 'Cannot run ' . executableName()) !== 0) {
            throw new RuntimeException("This Site data holds another release's application. Start "
                . executableName() . " once to lay this release's: $data");
        }
    } elseif (process($launcher, array_merge(['lay-app', $data], siteSettings()['writable']), $descriptors, $data, 'Cannot run ' . executableName()) !== 0) {
        throw new RuntimeException("Cannot lay the application in Site data: $data");
    }
    putenv('DRUPACK_RUNTIME_APP_DIR=' . $site->application());
}

// The packaged site's defaults, written from its drupack.yml when the application was built.
function siteSettings(): array
{
    static $site;
    return $site ??= json_decode((string) file_get_contents(__DIR__ . '/site.json'), true, 512, JSON_THROW_ON_ERROR);
}

function options(array $arguments, bool $drush, array $site): array
{
    $options = [
        'data-dir' => environment('DRUPACK_DATA_DIR') ?? './data',
        // The listener defaults after the recorded one is read, so an absent option is still visible here.
        'listen' => null,
        'host' => null,
        // The files directory falls back to the recorded one, then to Site data, once the Site data is known.
        'files-dir' => null,
        'database' => environment('DRUPACK_DATABASE') ?? 'sqlite',
        'db-host' => environment('DRUPACK_DB_HOST'),
        'db-port' => environment('DRUPACK_DB_PORT'),
        'db-name' => environment('DRUPACK_DB_NAME'),
        'db-user' => environment('DRUPACK_DB_USER'),
        'db-password' => environment('DRUPACK_DB_PASSWORD'),
        'admin-user' => environment('DRUPACK_ADMIN_USER'),
        'admin-password' => environment('DRUPACK_ADMIN_PASSWORD'),
        'site-name' => environment('DRUPACK_SITE_NAME') ?? $site['site_name'],
        'no-browser' => null,
        'foreground' => null,
    ];
    $command = [];
    while ($arguments !== []) {
        $argument = array_shift($arguments);
        if ($drush && !array_key_exists(substr(explode('=', $argument, 2)[0], 2), $options)) {
            $command = array_merge([$argument], $arguments);
            break;
        }
        if ($argument === '--help') {
            printf(HELP . "\n", executableName());
            exit(0);
        }
        $parts = explode('=', $argument, 2);
        $name = substr($parts[0], 2);
        // Launch arguments are user input, so reject unknown options and missing values.
        if (!str_starts_with($argument, '--') || !array_key_exists($name, $options)) {
            throw new InvalidArgumentException("Unknown argument: $argument");
        }
        if ($name === 'no-browser' || $name === 'foreground') {
            $options[$name] = '1';
            continue;
        }
        $value = $parts[1] ?? array_shift($arguments);
        if ($value === null || $value === '' || str_starts_with($value, '--')) {
            throw new InvalidArgumentException("Missing value for --$name");
        }
        $options[$name] = $value;
    }
    return [$options, $command];
}

// The generated password is never shown: the printed one-time login link signs the reader
// in directly, landing on the dashboard, so the password only keeps the account from being
// passwordless. It reaches only the Drupal step that sets it.
function administratorCredentials(array $options, array $steps): array
{
    if (!credentialsRequired($steps)) {
        return $options;
    }
    $options['admin-user'] ??= 'admin';
    $options['admin-password'] ??= bin2hex(random_bytes(32));
    return $options;
}

// The server process waits for its own first response, prints the readiness line and opens
// the browser when asked. A request spends a one-time login link, so readiness is polled on
// $url and the browser opens on $target. $target is a working credential for uid 1, so it
// enters the serving process's environment only when a browser will actually spend it: any
// PHP running inside that process can otherwise read it through getenv, $_ENV or phpinfo.
function openWhenServing(string $url, ?string $target, bool $browser): void
{
    putenv("DRUPACK_RUNTIME_URL=$url");
    // The server opens a browser when this variable is set, so a start that opens none
    // clears whatever the environment it inherited held.
    putenv($browser ? "DRUPACK_RUNTIME_OPEN=$target" : 'DRUPACK_RUNTIME_OPEN');
}

// The token names this Site data over HTTP without disclosing its path. Windows spells one
// path in several casings, so the hash reads a single one.
function siteToken(string $data): string
{
    return hash('sha256', windows() ? strtolower($data) : $data);
}

// `stop` takes --data-dir alone. Any other option is refused, so a start's options cannot
// reach a command that changes no site.
function stopDataDirectory(array $arguments): string
{
    $directory = environment('DRUPACK_DATA_DIR') ?? './data';
    while ($arguments !== []) {
        $argument = array_shift($arguments);
        if ($argument === '--help') {
            printf(HELP . "\n", executableName());
            exit(0);
        }
        $parts = explode('=', $argument, 2);
        if ($parts[0] !== '--data-dir') {
            throw new InvalidArgumentException("Unknown argument: $argument");
        }
        $directory = $parts[1] ?? array_shift($arguments);
        if ($directory === null || $directory === '' || str_starts_with($directory, '--')) {
            throw new InvalidArgumentException('Missing value for --data-dir');
        }
    }
    return $directory;
}

// Ends the server that holds the Serving lease over $directory. The directory is resolved
// but never created, so a stop on a mistyped path leaves nothing behind.
function stopSite(string $directory): int
{
    $resolved = realpath($directory);
    if ($resolved === false) {
        return notRunning();
    }
    $site = new SiteData(canonical($resolved));
    return stopServer($site->lease(), $site->stopRecord(), 'Site data', $site->directory);
}

// An IPv6 address takes brackets inside a URL authority.
function urlHost(string $host): string
{
    return str_contains($host, ':') ? "[$host]" : $host;
}

// Splits IP:PORT, an IPv6 address in brackets, into the bare address and the port.
function listenerParts(string $listen): array
{
    // Listener values enter Caddy configuration and must contain only an IP address and port.
    if (!preg_match('/^(\[[0-9a-fA-F:]+\]|[0-9.]+):([0-9]+)$/D', $listen, $listener)) {
        throw new InvalidArgumentException('--listen requires IP:PORT, with IPv6 enclosed in brackets');
    }
    return [trim($listener[1], '[]'), (int) $listener[2]];
}

// A login link and the session it opens cross any other network in clear text, so only
// a loopback listener opens a browser. 0.0.0.0 and :: accept other computers too.
function loopback(string $bind): bool
{
    return $bind === '::1' || str_starts_with($bind, '127.');
}

// Reports whether anything holds $bind:$port. A connect answers this on every platform,
// where a trial bind would report a taken port as free under Windows SO_REUSEADDR. A
// wildcard is probed on its own family's loopback, since an IPv6-only listener never
// answers on 127.0.0.1.
function portTaken(string $bind, int $port): bool
{
    $host = match ($bind) {
        '0.0.0.0' => '127.0.0.1',
        '::' => '::1',
        default => $bind,
    };
    $probe = @stream_socket_client('tcp://' . urlHost($host) . ":$port", $code, $error, 1);
    if ($probe === false) {
        return false;
    }
    fclose($probe);
    return true;
}

// Where the running server serves, read from the record that start wrote, so a handover
// names the address that server took rather than the one this start asked for. Returns
// its bind address and its URL.
function servedListener(SiteData $site, array $options): array
{
    $record = $site->listener() ?? $options;
    [$bind, $port] = listenerParts($record['listen']);
    return [$bind, 'http://' . urlHost($record['host']) . ":$port/"];
}

// An option the reader gave beats the recorded listener. Site data written before the
// record exists falls back to the listener defaults.
function recordedListener(array $options, ?array $record): array
{
    if ($record === null) {
        return $options;
    }
    $options['listen'] ??= $record['listen'];
    $options['host'] ??= $record['host'];
    return $options;
}

// Every start and `drush` keep the files directory the last start named, since the
// site's files live there.
function recordedFilesDirectory(array $options, ?array $record): array
{
    $options['files-dir'] ??= $record['files-dir'] ?? null;
    return $options;
}

function credentialsRequired(array $steps): bool
{
    return array_intersect(['administrator', 'install'], $steps) !== [];
}

// A first start on a database server takes its connection from the command line. SQLite needs
// none, and a resumed start reads the connection from the recorded settings.
function requireDatabaseOptions(array $options, array $steps): void
{
    if (!in_array('settings', $steps, true) || $options['database'] === 'sqlite') {
        return;
    }
    foreach (['db-host', 'db-name', 'db-user', 'db-password'] as $name) {
        if ($options[$name] === null) {
            throw new RuntimeException("Missing database connection details for {$options['database']}");
        }
    }
}

// A site built without a recipe ships no seed, so a SQLite first start has nothing to copy.
function requireSeed(array $steps, array $site): void
{
    if (in_array('seed', $steps, true) && $site['recipe'] === '') {
        throw new RuntimeException(executableName() . ' has no recipe to seed a SQLite site. '
            . 'Start it with --database mysql or --database pgsql and the connection details of the database that holds its site.');
    }
}

// One start at a time initializes a Site data directory. The resolved path gives equivalent paths one lock.
function databasePort(array $options): string
{
    return $options['db-port'] ?? ($options['database'] === 'mysql' ? '3306' : '5432');
}

function databaseConfiguration(array $options, SiteData $site): array
{
    if ($options['database'] === 'sqlite') {
        return [
            'driver' => 'sqlite',
            'database' => $site->database(),
            'namespace' => 'Drupal\\sqlite\\Driver\\Database\\sqlite',
            'autoload' => 'core/modules/sqlite/src/Driver/Database/sqlite/',
        ];
    }
    $port = databasePort($options);
    if (filter_var($port, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1, 'max_range' => 65535]]) === false) {
        throw new InvalidArgumentException('Invalid database port');
    }
    return [
        'driver' => $options['database'],
        'database' => $options['db-name'],
        'username' => $options['db-user'],
        'password' => $options['db-password'],
        'host' => $options['db-host'],
        'port' => (int) $port,
        'prefix' => '',
    ];
}

function settings(string $template, array $database, string $siteSettings): string
{
    $content = file_get_contents($template);
    if ($content === false) {
        throw new RuntimeException('Cannot read Drupal settings template');
    }
    return str_replace(
        ['__DRUPACK_DATABASE_CONFIGURATION__', '__DRUPACK_SITE_SETTINGS__'],
        [var_export($database, true), var_export($siteSettings, true)],
        $content,
    );
}

// A serving site requires this file on every request, and a `drush` command runs while it
// serves. The replacement is written beside it and renamed over it, so a request reads
// the old file or the new one; a truncating write would let one read half of it.
function writeSettings(string $path, string $template, array $database, string $siteSettings): void
{
    $staging = "$path.new";
    if (file_put_contents($staging, settings($template, $database, $siteSettings)) === false || !rename($staging, $path)) {
        throw new RuntimeException('Cannot initialize Drupal settings');
    }
}

// The recorded settings decide the backend once they exist, so later starts need no database options.
function recordedOptions(array $options, SiteData $site): array
{
    $recorded = $site->connection();
    $options['database'] = $recorded['driver'];
    if ($recorded['driver'] !== 'sqlite') {
        $options['db-host'] = $recorded['host'];
        $options['db-port'] = (string) $recorded['port'];
        $options['db-name'] = $recorded['database'];
        $options['db-user'] = $recorded['username'];
        $options['db-password'] = $recorded['password'];
    }
    return $options;
}

// DIAGNOSTIC_LIMIT bounds how much of a failed step's explanation reaches the terminal.
// Drush prints its reason first and its backtrace after, so the head is the useful end.
const DIAGNOSTIC_LIMIT = 400;

// Reads what Drush wrote to stderr, as one line a reader can act on. A failing step can
// print the connection as a URL carrying its password, so the credentials go before
// anything prints.
function diagnostic(string $path): string
{
    $text = preg_replace('#(?<=://)[^:@/\s]+:[^@/\s]+(?=@)#', 'USER:PASSWORD', (string) file_get_contents($path));
    $text = trim((string) preg_replace('/\s+/', ' ', $text));
    return strlen($text) > DIAGNOSTIC_LIMIT ? substr($text, 0, DIAGNOSTIC_LIMIT) . '...' : $text;
}

function runDrush(string $binary, array $command, string $failure): void
{
    $errors = tempnam(sys_get_temp_dir(), 'drupack-step-');
    if ($errors === false) {
        throw new RuntimeException('Cannot create a temporary file for the step diagnostic');
    }
    try {
        // stderr is a file, not a pipe, for the reason drushLoginLink() states: nothing here
        // drains a pipe while the child runs, so a full one would deadlock.
        $descriptors = [0 => ['file', nullDevice(), 'r'], 1 => ['file', nullDevice(), 'w'], 2 => ['file', $errors, 'w']];
        $exitCode = process($binary, array_merge(['php-cli'], $command), $descriptors, application(), $failure);
        $reason = $exitCode === 0 ? '' : diagnostic($errors);
    } finally {
        unlink($errors);
    }
    if ($exitCode !== 0) {
        throw new RuntimeException($reason === '' ? $failure : "$failure: $reason");
    }
}

function drushPath(): string
{
    return application() . '/vendor/drush/drush/drush.php';
}

// Reads one Drush field. An unusable site answers with anything but the expected value.
function drushField(string $binary, array $command): string
{
    $descriptors = [0 => ['file', nullDevice(), 'r'], 1 => ['pipe', 'w'], 2 => ['file', nullDevice(), 'w']];
    $child = proc_open(array_merge([$binary, 'php-cli', drushPath()], $command), $descriptors, $pipes, application());
    if (!is_resource($child)) {
        throw new RuntimeException('Cannot run Drush');
    }
    $output = stream_get_contents($pipes[1]);
    fclose($pipes[1]);
    proc_close($child);
    return trim((string) $output);
}

// Drush addresses the site through DRUSH_OPTIONS_URI. The site is not serving yet, and the
// Go entrypoint opens a browser once it answers.
function loginLink(string $binary, string $url, string $destination): string
{
    return drushLoginLink($binary, drushPath(), application(), [$destination], $url);
}

// Names the reason Drush gave for a failed mint, and the command that mints one by hand.
function explainMintFailure(LoginLinkFailure $failure, string $data): void
{
    $reason = rtrim($failure->reason, '. ');
    fwrite(STDERR, 'Cannot mint a one-time login link' . ($reason === '' ? '' : ": $reason")
        . ". Get one with: " . executableName() . " drush --data-dir $data user:login /admin/dashboard\n");
}

// A start whose address this Site data already serves runs no server of its own: two
// FrankenPHP processes over one database and one runtime directory would corrupt both.
function handOver(string $binary, string $url, string $data, bool $browser): never
{
    fwrite(STDOUT, "Creating a one-time login link.\n");
    try {
        $link = loginLink($binary, $url, '/admin/dashboard');
    } catch (LoginLinkFailure $failure) {
        $link = null;
        explainMintFailure($failure, $data);
    }
    fwrite(STDOUT, executableName() . " is already serving this Site data.\n\n  URL:    $url\n"
        . ($link === null ? '' : "  Login:  $link\n"));
    if ($link === null || !$browser) {
        exit(0);
    }
    // The link is a working credential, so it reaches the opener through the environment,
    // which only this user can read, rather than through a command line every local
    // account can list.
    putenv("DRUPACK_RUNTIME_OPEN=$link");
    replaceProcess($binary, ['browser-open'], application(), 'Cannot open the browser');
}

function databaseHoldsTables(array $options): bool
{
    $connection = new PDO(
        sprintf('%s:host=%s;port=%s;dbname=%s', $options['database'], $options['db-host'], databasePort($options), $options['db-name']),
        $options['db-user'],
        $options['db-password'],
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION],
    );
    // PostgreSQL resolves its own schemas from the search path, which need not name public first.
    $schema = $options['database'] === 'mysql' ? '= DATABASE()' : '= ANY(current_schemas(false))';
    $statement = $connection->query("SELECT count(*) FROM information_schema.tables WHERE table_schema $schema");
    return (int) $statement->fetchColumn() > 0;
}

function installDrupal(array $options, string $binary): void
{
    $drush = drushPath();
    $recipe = application() . '/' . siteSettings()['recipe'];
    if (!is_file($drush) || !is_dir($recipe)) {
        throw new RuntimeException('Bundled Drupal installation files are unavailable');
    }
    // Every local account can list a process's arguments, so the database credentials
    // come from the settings step's settings.php and the password from the environment.
    runDrush($binary, [
        $drush,
        'site:install',
        $recipe,
        '--yes',
        '--account-name=' . $options['admin-user'],
        '--site-name=' . $options['site-name'],
    ], 'Drupal installation failed');
    configureAdministrator($binary);
}

// The database is the user's only copy: an installed site is kept, and other tables stop the start.
// A database this initialization began installing into held no tables then, so a site that
// boots there now may have been cut off mid-recipe, and it is never adopted. Its tables stay
// until a person empties the database: nothing here proves they are still the install's own.
function installSite(SiteData $site, array $options, string $binary): bool
{
    $started = $site->installStarted();
    // Without the recorded settings the options come from the command line, which may name
    // any database, so a resume names none of them to empty.
    if ($started && !file_exists($site->settings())) {
        throw new RuntimeException("This Site data holds an interrupted installation but no settings.php: $site->directory. "
            . "Restore its settings.php, or start " . executableName() . " with an empty Site data directory.");
    }
    if (!$started && drushField($binary, ['status', '--field=bootstrap']) === 'Successful') {
        fwrite(STDOUT, "This database already holds a site. " . executableName() . " enabled nothing on it, and keeps its own administrator account.\n");
        return true;
    }
    if (siteSettings()['recipe'] === '') {
        throw new RuntimeException("The database for $site->directory holds no installed site, and " . executableName()
            . " has no recipe to install one. Name the database that holds its site, then start " . executableName() . " again.");
    }
    if (databaseHoldsTables($options)) {
        if ($started) {
            throw new RuntimeException("This Site data began installing into the {$options['database']} database {$options['db-name']} on "
                . urlHost($options['db-host']) . ':' . databasePort($options) . ", which now holds tables: $site->directory. "
                . "If they are that installation's, empty the database, then start " . executableName() . " again. "
                . "If it holds a site of yours, start " . executableName() . " with an empty Site data directory.");
        }
        throw new RuntimeException("The database for $site->directory holds tables without an installed site. Empty it or name another database, then start " . executableName() . " again.");
    }
    if (!$started) {
        $site->startInstall();
    }
    installDrupal($options, $binary);
    return false;
}

// The Dockerfile installs the seed with this password, on the site:install line that
// builds /app/seed, and tests/initialization.sh checks that they match. It ships in
// the Dockerfile and in every executable.
function seedPassword(): string
{
    return 'drupack-seed-password';
}

// File presence cannot tell a finished site from an interrupted one, so adoption asks Drupal.
// A first start interrupted before its administrator step can still bootstrap, with the seed
// password in place, and adoption must not hand that back: the password is public. The name
// is not a signal: a site installed with --admin-user drupack-admin is a legitimate account.
function adoptSite(string $data, string $binary): void
{
    if (drushField($binary, ['status', '--field=bootstrap']) !== 'Successful') {
        throw new RuntimeException("This Site data holds settings but no installed site: $data. Inspect it with: " . executableName() . " drush --data-dir $data status");
    }
    $expression = '$account = \\Drupal\\user\\Entity\\User::load(1); print \\Drupal::service("password")->check('
        . var_export(seedPassword(), true) . ', $account->getPassword()) ? "yes" : "no";';
    if (drushField($binary, ['php:eval', $expression]) === 'yes') {
        throw new RuntimeException("This Site data holds a site whose administrator still accepts the packaged seed password: $data. "
            . "Set a new password, then start " . executableName() . " again: " . executableName() . " drush --data-dir $data php:eval "
            . '\'$account = \\Drupal\\user\\Entity\\User::load(1); $account->setPassword("new-password"); $account->save();\'');
    }
}

function copySeed(SiteData $site): void
{
    $seed = application() . '/seed';
    if (!copy("$seed/site.sqlite", $site->database())) {
        throw new RuntimeException('Cannot initialize the Seed site database');
    }
    $files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator("$seed/files", FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::SELF_FIRST);
    foreach ($files as $file) {
        $destination = getenv('DRUPACK_RUNTIME_FILES_DIR') . '/' . $files->getSubPathName();
        if ($file->isDir()) {
            directory($destination);
        } elseif (!copy($file->getPathname(), $destination)) {
            throw new RuntimeException("Cannot initialize Seed site file: $destination");
        }
    }
}

function clearSeedCaches(SiteData $site): void
{
    $database = new PDO('sqlite:' . $site->database());
    $tables = $database->query("SELECT name FROM sqlite_master WHERE type = 'table' AND name GLOB 'cache_*'");
    foreach ($tables as $table) {
        $database->exec('DELETE FROM "' . str_replace('"', '""', $table['name']) . '"');
    }
}

function configureAdministrator(string $binary): void
{
    runDrush($binary, [drushPath(), 'php:eval', '$account = \\Drupal\\user\\Entity\\User::load(1); $account->set("name", getenv("DRUPACK_ADMIN_USER")); $account->setPassword(getenv("DRUPACK_ADMIN_PASSWORD")); $account->save();'], 'Cannot configure Drupal administrator');
}

// Drush names the seed when the Dockerfile installs it. The first start renames it, so a
// seeded site and an installed one carry the same name.
function configureSeedSiteName(string $binary, string $name): void
{
    runDrush($binary, [drushPath(), 'config:set', 'system.site', 'name', $name, '--yes'], 'Cannot set the site name');
}

// Drupal CMS recipes enable these during site:install; the seed build removes them the
// same way. automatic_updates 4.1.0 stalls a cron request, and package_manager cannot
// write into the read-only application. A resumed modules step can run after an earlier one
// already removed them, and Drush refuses to uninstall a module that is not enabled.
function removeRecipeModules(string $binary): void
{
    $enabled = json_decode(drushField($binary, ['pm:list', '--status=enabled', '--format=json']), true, 512, JSON_THROW_ON_ERROR);
    $present = array_intersect(['automatic_updates', 'package_manager'], array_keys($enabled));
    if ($present !== []) {
        runDrush($binary, array_merge([drushPath(), 'pm:uninstall'], $present, ['--yes']), 'Cannot remove automatic updates');
    }
}

// What each initialization step tells the person waiting. A first start spends minutes
// inside one of these, and prints nothing else until the site answers.
const STEP_REPORTS = [
    'seed' => 'Copying the packaged site into Site data',
    'settings' => 'Writing the site settings',
    'install' => 'Installing the site',
    'modules' => 'Removing modules the application cannot run',
    'administrator' => 'Creating the administrator account',
    'adopt' => 'Adopting the site already in Site data',
];

// Returns whether the step found a site already installed in the database.
function runStep(string $step, SiteData $site, array $options, string $binary, bool $adopted): bool
{
    switch ($step) {
        case 'seed':
            copySeed($site);
            clearSeedCaches($site);
            return false;
        case 'settings':
            // A repeated step keeps the existing secret, so the site's sessions and tokens survive it.
            if (!file_exists($site->secret())
                && file_put_contents($site->secret(), bin2hex(random_bytes(32)), LOCK_EX) === false) {
                throw new RuntimeException('Cannot initialize the site secret');
            }
            writeSettings($site->settings(), application() . '/settings.php', databaseConfiguration($options, $site), siteSettings()['settings']);
            return false;
        case 'administrator':
            configureAdministrator($binary);
            configureSeedSiteName($binary, $options['site-name']);
            return false;
        case 'install':
            return installSite($site, $options, $binary);
        case 'modules':
            if (!$adopted) {
                removeRecipeModules($binary);
            }
            return false;
        case 'adopt':
            adoptSite($site->directory, $binary);
            return false;
        default:
            throw new RuntimeException("Unknown initialization step: $step");
    }
}

// application/tests/launch_test.php defines this to load the functions above without starting a site.
if (defined('DRUPACK_LAUNCH_LIBRARY')) {
    return;
}

try {
    if (environment('DRUPACK_RUNTIME_STOP') === '1') {
        exit(stopSite(fromStartDirectory(stopDataDirectory(array_slice($argv, 1)))));
    }
    $drush = environment('DRUPACK_RUNTIME_DRUSH') === '1';
    [$options, $command] = options(array_slice($argv, 1), $drush, siteSettings());
    $written = $options['data-dir'];
    $options['data-dir'] = fromStartDirectory($written);
    if ($options['files-dir'] !== null) {
        $options['files-dir'] = fromStartDirectory($options['files-dir']);
    }
    // PHP_BINARY is empty in embedded FrankenPHP; the Go entrypoint exports its own path.
    $binary = getenv('DRUPACK_RUNTIME_BINARY');
    if ($drush && in_array($command[0] ?? '', ['--help', '-h', 'list'], true)) {
        replaceProcess($binary, array_merge(['php-cli', drushPath()], $command), application(), 'Cannot run Drush');
    }
    // Launch arguments are user input, so the backend must name a supported driver.
    if (!in_array($options['database'], ['sqlite', 'mysql', 'pgsql'], true)) {
        throw new InvalidArgumentException('--database requires sqlite, mysql, or pgsql');
    }
    $steps = [];
    // The directory as named, before it exists and resolves.
    $named = new SiteData($options['data-dir']);
    if ($drush) {
        // `drush` initializes nothing and takes no lease, so Drush works while the server runs.
        if (!file_exists($named->settings())) {
            throw new RuntimeException("This Site data has no site yet: {$options['data-dir']}. Start " . executableName() . " once to create one.");
        }
        // `drush` serves nothing of its own, so it addresses the site where the last start served.
        $options = recordedListener($options, $named->listener());
    } else {
        $steps = $named->steps($options['database']);
        requireSeed($steps, siteSettings());
        $options = administratorCredentials($options, $steps);
    }
    $options['listen'] ??= '127.0.0.1:' . siteSettings()['port'];
    $options['host'] ??= 'localhost';
    requireDatabaseOptions($options, $steps);
    [$bind, $port] = listenerParts($options['listen']);
    if (!filter_var($bind, FILTER_VALIDATE_IP) || $port < 1 || $port > 65535) {
        throw new InvalidArgumentException('Invalid listener address or port');
    }
    // The permitted request host is external input and is converted to an exact Drupal pattern.
    if (!filter_var($options['host'], FILTER_VALIDATE_DOMAIN, FILTER_FLAG_HOSTNAME)
        && !filter_var($options['host'], FILTER_VALIDATE_IP)) {
        throw new InvalidArgumentException('Invalid --host value');
    }
    // The log path reaches the Caddyfile through the environment, which Caddy splices in before it
    // reads quotes, so a quote breaks it.
    if (str_contains($options['data-dir'], '"')) {
        throw new InvalidArgumentException('--data-dir must not contain a double quote');
    }
    // The files directory reaches the Caddyfile the same way.
    if (str_contains((string) $options['files-dir'], '"')) {
        throw new InvalidArgumentException('--files-dir must not contain a double quote');
    }

    umask(0077);
    directory($options['data-dir']);
    // realpath() resolves in the native form, so the result is re-canonicalised
    // before it travels into every export, hash and printed line that follows.
    $data = canonical(realpath($options['data-dir']));
    $site = new SiteData($data);
    $site->prepare();
    $options = recordedFilesDirectory($options, $site->listener());
    $files = $options['files-dir'] ?? $site->files();
    directory("$files/translations");
    $files = canonical(realpath($files));
    // A named directory is recorded resolved. The default stays unrecorded, so it moves with Site data.
    if ($options['files-dir'] !== null) {
        $options['files-dir'] = $files;
    }
    putenv("DRUPACK_RUNTIME_DATA_DIR=$data");
    putenv("DRUPACK_RUNTIME_FILES_DIR=$files");
    // Drupal matches its trusted host patterns against the request's host, which keeps an
    // IPv6 address's brackets.
    putenv('DRUPACK_RUNTIME_HOST=' . urlHost($options['host']));
    // The address a reader types, never the bind address. Drush builds absolute URLs from this
    // variable. Without it Drupal falls back to http://default, and every printed or mailed
    // link names an unreachable host.
    $url = 'http://' . urlHost($options['host']) . ":$port/";
    putenv("DRUSH_OPTIONS_URI=$url");
    $logPath = $site->logs() . '/caddy.log';
    $runtime = canonical(realpath($site->runtime()));
    // Caddy state and every temporary file stay beside the site they belong to.
    putenv("TMPDIR=$runtime");
    putenv("TEMP=$runtime");
    putenv("TMP=$runtime");
    putenv("XDG_DATA_HOME=$runtime");
    putenv("XDG_CONFIG_HOME=$runtime");
    foreach ([
        'database' => 'DRUPACK_DATABASE',
        'db-host' => 'DRUPACK_DB_HOST',
        'db-port' => 'DRUPACK_DB_PORT',
        'db-name' => 'DRUPACK_DB_NAME',
        'db-user' => 'DRUPACK_DB_USER',
        'db-password' => 'DRUPACK_DB_PASSWORD',
        'admin-user' => 'DRUPACK_ADMIN_USER',
        'admin-password' => 'DRUPACK_ADMIN_PASSWORD',
        'site-name' => 'DRUPACK_SITE_NAME',
    ] as $option => $environment) {
        if ($options[$option] !== null) {
            putenv("$environment={$options[$option]}");
        }
    }
    // Both questions are asked before the listener record and every install step, so a
    // served site and a taken port each reach their reader as a sentence rather than as
    // a bind error or a corrupted database.
    $lease = null;
    if (!$drush) {
        $lease = takeLease($site->lease());
        if ($lease === null) {
            // The holder is still installing while no completion marker exists, and
            // serving once it does. A handover addresses a site that answers requests,
            // so an installation in progress refuses instead.
            if (!$site->installed()) {
                throw new RuntimeException("Another " . executableName() . " start is preparing this Site data: $data");
            }
            [$servedBind, $served] = servedListener($site, $options);
            if (personPresent()) {
                handOver($binary, $served, $data, $options['no-browser'] === null && loopback($servedBind));
            }
            throw new RuntimeException(executableName() . " already serves this Site data at $served: $data");
        }
        if (portTaken($bind, $port)) {
            throw new RuntimeException("Another program is listening on {$options['listen']}. Stop it, or start on"
                . " a free port: " . executableName() . " --listen $bind:" . ($port + 1));
        }
        // A record from an earlier server names a port and a token nobody listens on, and
        // `stop` reads a missing record as a start still preparing.
        if (file_exists($site->stopRecord())) {
            unlink($site->stopRecord());
        }
        // A double-click owns its console, which closing the window would end along with a
        // background server, so it serves where the reader can stop it.
        if ($options['foreground'] === null && !consoleOwned()) {
            detachServer($lease, $site->serverLog(),
                stopCommand($written === './data' ? '' : ' --data-dir ' . shellWord($written)), array_slice($argv, 1));
        }
        $site->recordListener($options['listen'], $options['host'], $options['files-dir']);
    }
    if (siteSettings()['writable'] !== []) {
        useSiteApplication($site, $drush);
    }
    if ($steps !== []) {
        // Read again under the lease: another start may have finished initializing between
        // the first read and the moment this one claimed the Site data.
        $steps = $site->steps($options['database']);
    }
    // A start refreshes the recorded settings from the template this release ships, so a
    // site installed by an earlier release gains the settings this one added. The
    // recorded connection details come back unchanged. A `drush` command reads that site
    // and writes nothing to it, since the file it would rewrite is being required by
    // the server answering requests.
    if (!$drush && file_exists($site->settings())) {
        // A pending settings step writes the file itself, so its contents are read once they are final.
        if (!in_array('settings', $steps, true)) {
            $options = recordedOptions($options, $site);
            writeSettings($site->settings(), application() . '/settings.php', databaseConfiguration($options, $site), siteSettings()['settings']);
        }
    }
    // The remaining steps reach the disk before the first one changes anything, and the
    // completion marker follows the last one.
    $number = 0;
    $adopted = $site->initialize($steps, function (string $step, bool $adopted) use (&$number, $steps, $site, $options, $binary): bool {
        fwrite(STDOUT, sprintf("[%d/%d] %s\n", ++$number, count($steps), STEP_REPORTS[$step]));
        return runStep($step, $site, $options, $binary, $adopted);
    });
    foreach (glob(application() . '/translations/*.po') as $translation) {
        $destination = "$files/translations/" . basename($translation);
        if (!file_exists($destination) && !copy($translation, $destination)) {
            throw new RuntimeException("Cannot install translation resource: $destination");
        }
    }
    if ($drush) {
        exit(process($binary, array_merge(['php-cli', drushPath()], $command), [0 => STDIN, 1 => STDOUT, 2 => STDERR], application(), 'Cannot run Drush'));
    }
    // Every start hands its reader a one-time way in, signed in as the administrator account,
    // uid 1, landing on the dashboard. A start that generated the password has no other way
    // in, so it still fails when the mint fails. An adopted site keeps its own accounts, and
    // it and every other start serve without the link.
    fwrite(STDOUT, "Creating a one-time login link.\n");
    try {
        $link = loginLink($binary, $url, '/admin/dashboard');
    } catch (LoginLinkFailure $failure) {
        if (credentialsRequired($steps) && !$adopted) {
            throw $failure;
        }
        $link = null;
        explainMintFailure($failure, $data);
    }
    // The addresses and paths only, never a readiness claim: the server binds after this
    // process execs into it, so the process that answers a request announces that itself.
    $details = "  URL:       $url\n" . ($link === null ? '' : "  Login:     $link\n");
    fwrite(STDOUT, $details . "  Site data: $data\n  Log:       $logPath\n");
    // A start with a terminal on standard input opens the browser for the person who ran
    // it, first start or later. A script, a container and a test have none, so they get
    // none. A file manager on Windows has no other way to reach its reader. A start with
    // no link has nothing to open.
    $browser = $link !== null && $options['no-browser'] === null && personPresent() && loopback($bind);
    if ($link !== null && !loopback($bind)) {
        fwrite(STDOUT, "No browser opens: {$options['listen']} accepts other computers over plain HTTP."
            . " Sign in from another computer only through a TLS proxy.\n");
    }
    openWhenServing($url, $link, $browser);
    // Every step that needed the administrator password has run. The server inherits
    // this environment and passes it to every process it starts, including PHP code a
    // site runs, so the credential stops here.
    putenv('DRUPACK_ADMIN_PASSWORD');
    fwrite(STDOUT, "Starting the web server.\n");
    // The Caddyfile the application ships is fixed, and Caddy fills its values from this environment.
    exportServerEnvironment([
        'DRUPACK_RUNTIME_PORT' => (string) $port,
        'DRUPACK_RUNTIME_BIND' => $bind,
        'DRUPACK_RUNTIME_ID' => siteToken($data),
        // Absolute, because FrankenPHP resolves a relative docroot against the directory
        // its process started in, which on Unix is the shared application whatever the
        // entry point changes to.
        'DRUPACK_RUNTIME_DOCROOT' => application() . '/' . siteSettings()['docroot'],
        'DRUPACK_RUNTIME_LOG_PATH' => $logPath,
        'DRUPACK_RUNTIME_STOP_RECORD' => $site->stopRecord(),
    ]);
    replaceProcess($binary, ['php-server', application() . '/Caddyfile'], application(), 'Cannot start FrankenPHP');
} catch (Throwable $error) {
    fwrite(STDERR, $error->getMessage() . "\n");
    exit(1);
}
