include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  _ALL_VALIDATE_ALLOW_FAILURE: "0"
  # Files copied from WordPress.
  _CSPELL_IGNORE_PATHS: 'js/script-modules/**,src/WordPress/StyleEngine/Vendor/**,modules/wordpal_convert/src/WordPress/WpBlockParser*.php'
